version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./infra/nginx/conf.d/yetla.upstream.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/docker-entrypoint.d:/docker-entrypoint.d:ro
      - ./apps/default:/usr/share/nginx/html:ro
      - type: bind
        source: /root/ssl
        target: /etc/nginx/ssl
        read_only: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/data
    env_file:
      - ./.env
