version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/conf.d/subdomains.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/default:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/data
    env_file:
      - ./.env
