version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/conf.d/yetla.upstream.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/docker-entrypoint.d:/docker-entrypoint.d:ro
      - type: bind
        source: /root/ssl
        target: /etc/nginx/ssl-src
        read_only: true
      - nginx_ssl_cache:/etc/nginx/ssl
    environment:
      - SSL_SOURCE_DIR=/etc/nginx/ssl-src
      - SSL_TARGET_DIR=/etc/nginx/ssl
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/data
    env_file:
      - ./.env

volumes:
  nginx_ssl_cache:
